#load "Enigma.fs"
open Enigma

(*
TAGESSCHLUESSEL:
    B425: Rotor settings UKWB IV II V
    agm: Ring settings a->1 g->7 m->13
    DM EP FL HI JR KY NQ OU SW TZ -> Plugboard  
KOPF:
    kr: war relevant (due to unique sound in morse code)
    2300: time of encryption -> 11pm
    182: Number of characters in message
    ZZXpwq: To get the right personal base settings of the rotors you have to set the rotors to ZZX and type pwq. The resulting characters are the new rotor positions to set.
*)



////v1              Message No. 233 of 19 July 1941 
//TAGESSCHLUESSEL:  B425 agm DM EP FL HI JR KY NQ OU SW TZ 
//KOPF:             kr-2300-182-ZZXpwq
Enigma.String.de_encrypt ('Z','Z','X') Rotor.UKW_B Rotor.IV Rotor.II Rotor.V [|"DM";"EP";"FL";"HI";"JR";"KY";"NQ";"OU";"SW";"TZ"|] (1,7,13) "PWQ"
    //SPRUCHSCHLUESSEL: QAY

Enigma.String.de_encrypt ('Q','A','Y') Rotor.UKW_B Rotor.IV Rotor.II Rotor.V [|"DM";"EP";"FL";"HI";"JR";"KY";"NQ";"OU";"SW";"TZ"|] (1,7,13) 
    "QKXETVPZQOHSXMBIZPHTCTRMAUZYSTJIMDUYOZBFRTZOUHBGOROUVRQEJRDRJHZPZIBQQHKMMJZCIIRCUOLXLCIOgKHRLIGGFJFTLLGDRARDZQUQKLTKXXXYKRUVFULBQLAYRZVJFULCGQJXFJURMURSELYFVFOKUHYUHSYLOMEFYAIIP"
//Übersetzung: "WIEVIELKLEINSIEGFRIEDGWOSMFRIEDRICHXHEINWIGHMUNXINSQRZAQTEINSSIEBENSTRIQAINSAQHXSIEBENWINXPLESNAUXABGEHOLTFRAGEXWERPZKMEFYHLKOMMADOHZATZUXOLENFRAGOVUNKANTWORTXDERQNAATYEKVEVSTER"
//             "WIE VIEL sFH (schwere Feldhaubitze) MUN. INSGESAMT 17.-18.07. WIRD PLESNAU ABGEHOLT FRAGE WER P---ZK MEFYHL KOMMA DOHZ ATZUXOLEN FRAGO VUNKANTWORT DER QNAATYEKVEVSTER"
   
    
////v2              Message No. 25 of 13 July 1941 
//TAGESSCHLUESSEL:  B423 gto AD EH GY IM KN LR OZ QV TX UW 
//Kopf:             xxxx-0830-219-HLCzmz
Enigma.String.de_encrypt ('H','L','C') Rotor.UKW_B Rotor.IV Rotor.II Rotor.III [|"AD";"EH";"GY";"IM";"KN";"LR";"OZ";"QV";"TX";"UW"|] (7,20,15) "zmz"
    //SPRUCHSCHLUESSEL: SDV

Enigma.String.de_encrypt ('S','D','V') Rotor.UKW_B Rotor.IV Rotor.II Rotor.III [|"AD";"EH";"GY";"IM";"KN";"LR";"OZ";"QV";"TX";"UW"|] (7,20,15) 
    "FDZCJJDKVWPYFDWPOQZGTJQYYXAFRHSQESERKGJBWBYPEOOKFMMPOMKQDDOLCPKHYPGUZYXBZYANYSAXIPXVQCPJBFFFDRDXFIJJPPPEYALCYKVLKXQHWIRZANGWUJBWVJYCKESMJQRYKQHCQOKMMYWMCKVLZJDVZXRUMRMNWFDZBQGXJQAPFFFZTAHJQZPWQWNIVZWUIJTHOYXGDCOJUW"
//Übersetzung: "ANXPANZXGRUPPEXVIERXSIEGFRIEDSIEGFRIEDTONIXDIVXSTEHTSEITXEINSZWOXSIEBENXEINSEINSNULLNULLXUHRMITANFAENGENAMUNTERKUNFTSRAUMXKANNNIQTEINFLIESZENXDAXDRITTEXINFXDIVXUNDXAQTEXPANZXDIVXBLOQIERENUNDRANMBELEGTHALTEXDIVXKDRX"
//             "AN PANZ GRUPPE 4 SIEGFRIED SIEGFRIED TONI DIV STEHT SEIT 12.07. 11:00 UHR MIT ANFAENGEN AM UNTERKUNFTSRAUM. KANN NIQT EINFLIESZEN DA 3. INF DIV UND 8. PANZ DIV BLOQIEREN UND RANM BELEGT HALTE DIV KDR"


////v3              Message No. 30 of 22 August 1941 
//TAGESSCHLUESSEL:  B341 wgr AC BE HW IP JZ KY LU OS QR VX 
//Kopf:             (1930)-51-gfraha
Enigma.String.de_encrypt ('G','F','R') Rotor.UKW_B Rotor.III Rotor.IV Rotor.I [|"AC";"BE";"HW";"IP";"JZ";"KY";"LU";"OS";"QR";"VX"|] (23,7,18) "aha"
    //SPRUCHSCHLUESSEL: TOR

Enigma.String.de_encrypt ('T','O','R') Rotor.UKW_B Rotor.III Rotor.IV Rotor.I [|"AC";"BE";"HW";"IP";"JZ";"KY";"LU";"OS";"QR";"VX"|] (23,7,18) 
    "CFVUAHZHPIWNUCXTMJGXPMVWKFVHZJTJGXMSSDJYESRCNX"
//Übersetzung: "WOGEFEQTSSTANDQUARTIERMEISTERABTXROEMEINSBERTA" --> "WO GEFEQTSSTAND QUARTIERMEISTER ABT X ROEM EINS BERTA"


////v4              Message No. 94 of 24 September 1941 
//TAGESSCHLUESSEL:  B231 szi AQ BO CM DP EW FT HS JZ KX LU 
//Kopf:             (1200)-81-ncwttg
Enigma.String.de_encrypt ('N','C','W') Rotor.UKW_B Rotor.II Rotor.III Rotor.I [|"AQ";"BO";"CM";"DP";"EW";"FT";"HS";"JZ";"KX";"LU"|] (19,26,9) "TTG"
    //SPRUCHSCHLUESSEL: DRI

Enigma.String.de_encrypt ('D','R','I') Rotor.UKW_B Rotor.II Rotor.III Rotor.I [|"AQ";"BO";"CM";"DP";"EW";"FT";"HS";"JZ";"KX";"LU"|] (19,26,9) "PWCQFEZLPXGENCLBOXJFVWWPXOOGLRIPJKOUIOTCTNSLZDKYYJQNTVCTMPLUOAUNESZVKXRCTMHM"
//Übersetzung:  "UMZUG GEPAEQ TROSS UND REST KOMMANDO STOPFEN X SQRIFTLIQER BEFEHL UNTERWEGS X SCHNEIDDR X"
//              "UMZUG GEPAECK TROSS UND REST KOMMANDO STOPPEN X SCHRIFTLICHER BEFEHL UNTERWEGS. SCHNEIDER"
